### ISSUE TITLE
让我想到了刚学完的黑马旅游网

### ISSUE THREAD

**Issue by cutety** [ishiningway/open-lyta#2]
先star一哈,找个时间看看

**Comment by ishiningway** [comment]
> 先star一哈,找个时间看看

可以的，我最近有个升级一下技术栈的想法，比如我用的ssm换成sbm，然后把后台古老的jquery换成layui

**Comment by ishiningway** [comment]
还想拿vue和spring boot 搞个博客哈哈

**Comment by cutety** [comment]
> > 先star一哈,找个时间看看
> 
> 可以的，我最近有个升级一下技术栈的想法，比如我用的ssm换成sbm，然后把后台古老的jquery换成layui

sbm是啥呀
